#!/bin/bash
#SBATCH -J ASE_pvals
#SBATCH -N 1 # number of nodes
#SBATCH -n 20 # number of cores
#SBATCH --mem=32G # memory pool for all cores
#SBATCH -t 0-72:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
# example use: sbatch ASE_pvalues

cd $SLURM_SUBMIT_DIR

module load singularity

singularity exec /projects/carter-lab/atyler/Containers/R_klotho.sif R -e 'rmarkdown::render(here::here("Documents", "GTEx_Setup.Rmd"))'
